[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'KKPMW/moonshine-vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'MidnaPeach/neonwave.vim'
