[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'KKPMW/moonshine-vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
