[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'

# vimでペーストする時に自動的にペーストモードにする
# https://qiita.com/ryoff/items/ad34584e41425362453e
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'KKPMW/moonshine-vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'

[[plugins]]
repo = 'MidnaPeach/neonwave.vim'

[[plugins]]
repo = 'challenger-deep-theme/vim'
